### PR TITLE
Feature/docker17 upgrade

### PR DESCRIPTION
**Pull request by challa**
Upgrade of docker run time  from 1.12.3 to  latest stable docker version 17.06.1-ce

### CODE REVIEW

**Comment by ketakig12** [comment]
Can older blob be removed? https://github.com/challa/service-fabrik-boshrelease/blob/b745831748a094c2ca92fe560fcdb04f57c660c5/config/blobs.yml#L25

**Comment by challa** [comment]
The entry for 1.12.3 we can remove, 
the original blob still need stay as the blob store is shared across all landscapes  and if any docker nodes in production/staging landscapes the will need the 1.12.3 untill they are updated with 17.06

**Comment by ketakig12** [comment]
Please remove the blob, else the file will keep on growing. Do we need sanity test again after that?

**Comment by challa** [comment]
removed the blob entry from the  blobs.yml, the actual blob can only be removed from S3 once docker 17 is  updated across all the landscapes

**Comment by challa** [comment]
Did another round of sanity testing after the blob entry removal. testing is fine

**Pull request merged**
